using JmaXml.Generator;

namespace JmaXml.Tests;

public class CSharpEmitterTests
{
    private static readonly DictionaryModel EmptyDictionary = new("2000-01-01", []);

    private static string Uri(string prefix) => SchemaLoader.KnownNamespaces.First(n => n.Prefix == prefix).Uri;

    private static string? ClassNameOf(string prefix) => SchemaLoader.KnownNamespaces.First(n => n.Prefix == prefix).ClassName;

    private static SchemaModel SchemaOf(string prefix, params TypeModel[] types) =>
        new([new NamespaceModel(prefix, Uri(prefix), ClassNameOf(prefix), [.. types])], []);

    private static ElementModel Element(string name, string ns, TypeRef type, int minOccurs, bool unbounded, bool nillable = false) =>
        new(name, ns, false, name, type, minOccurs, unbounded, nillable);

    [Fact]
    public void Emits_one_file_per_namespace_plus_schema_info()
    {
        var files = CSharpEmitter.Emit(SchemaLoader.Load(Fixtures.XsdDir), DictionaryReader.Read(Fixtures.DictionaryPath));
        Assert.Equal(
            ["ElementBasis.g.cs", "InformationBasis.g.cs", "Jmx.g.cs", "Meteorology.g.cs", "SchemaInfo.g.cs", "Seismology.g.cs", "Volcanology.g.cs"],
            files.Keys.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void Header_and_no_carriage_return_are_emitted_for_every_file()
    {
        var files = CSharpEmitter.Emit(SchemaOf("jmx_seis"), EmptyDictionary);
        Assert.All(files.Values, f => Assert.StartsWith("// <auto-generated/>\n#nullable enable\n", f, StringComparison.Ordinal));
        Assert.All(files.Values, f => Assert.DoesNotContain("\r", f, StringComparison.Ordinal));
    }

    [Fact]
    public void Element_occurrence_controls_the_property_shape_read_case_and_initializer()
    {
        var seisUri = Uri("jmx_seis");
        var type = new TypeModel("type.Occurrences", seisUri, null, [],
        [
            Element("Name", seisUri, TypeRef.Simple(Primitive.String), 1, false),
            Element("Note", seisUri, TypeRef.Simple(Primitive.String), 0, false),
            Element("Tags", seisUri, TypeRef.Simple(Primitive.String), 0, true),
            Element("Entries", seisUri, TypeRef.Simple(Primitive.String), 1, true),
        ]);
        var files = CSharpEmitter.Emit(SchemaOf("jmx_seis", type), EmptyDictionary);
        var seis = files["Seismology.g.cs"];
        Assert.Contains("internal static Occurrences Read(JmaXmlReader r)", seis, StringComparison.Ordinal);
        Assert.Contains("public required string Name { get; init; }", seis, StringComparison.Ordinal);
        Assert.Contains("case \"Name\" when r.InNamespace(XmlNamespaces.Seismology): r.Once(ref nameSeen, \"Name\"); name = r.ReadString(); break;", seis, StringComparison.Ordinal);
        Assert.Contains("Name = name ?? throw r.Missing(in scope, \"Name\"),", seis, StringComparison.Ordinal);
        Assert.Contains("public string? Note { get; init; }", seis, StringComparison.Ordinal);
        Assert.Contains("case \"Note\" when r.InNamespace(XmlNamespaces.Seismology): r.Once(ref noteSeen, \"Note\"); note = r.ReadString(); break;", seis, StringComparison.Ordinal);
        Assert.Contains("Note = note,", seis, StringComparison.Ordinal);
        Assert.Contains("public ImmutableArray<string> Tags { get; init; } = [];", seis, StringComparison.Ordinal);
        Assert.Contains("case \"Tags\" when r.InNamespace(XmlNamespaces.Seismology): tags.Add(r, r.ReadString()); break;", seis, StringComparison.Ordinal);
        Assert.Contains("Tags = tags.ToImmutable(r),", seis, StringComparison.Ordinal);
        Assert.Contains("public required ImmutableArray<string> Entries { get; init; }", seis, StringComparison.Ordinal);
        Assert.Contains("case \"Entries\" when r.InNamespace(XmlNamespaces.Seismology): entries.Add(r, r.ReadString()); break;", seis, StringComparison.Ordinal);
        Assert.Contains("Entries = entries.IsEmpty ? throw r.Missing(in scope, \"Entries\") : entries.ToImmutable(r),", seis, StringComparison.Ordinal);
        Assert.Contains("default: r.Skip(); break;", seis, StringComparison.Ordinal);
    }

    [Fact]
    public void Repeated_complex_element_named_like_its_type_qualifies_the_read_call_with_global()
    {
        var seisUri = Uri("jmx_seis");
        var wrap = new TypeModel("type.Wrap", seisUri, null, [], [Element("Sample", seisUri, TypeRef.Complex(seisUri, "type.Sample"), 0, true)]);
        var sample = new TypeModel("type.Sample", seisUri, null, [], []);
        var files = CSharpEmitter.Emit(SchemaOf("jmx_seis", wrap, sample), EmptyDictionary);
        var seis = files["Seismology.g.cs"];
        Assert.Contains("public ImmutableArray<Sample> Sample { get; init; } = [];", seis, StringComparison.Ordinal);
        Assert.Contains("case \"Sample\" when r.InNamespace(XmlNamespaces.Seismology): sample.Add(r, global::JmaXml.Seismology.Sample.Read(r)); break;", seis, StringComparison.Ordinal);
        Assert.Contains("Sample = sample.ToImmutable(r),", seis, StringComparison.Ordinal);
    }

    [Fact]
    public void Simple_content_reads_attributes_before_the_value()
    {
        var ebUri = Uri("jmx_eb");
        var type = new TypeModel("type.Measurement", ebUri, Primitive.Float,
            [new AttributeModel("kind", Primitive.String, true), new AttributeModel("unit", Primitive.String, false)], []);
        var files = CSharpEmitter.Emit(SchemaOf("jmx_eb", type), EmptyDictionary);
        var eb = files["ElementBasis.g.cs"];
        Assert.Contains("public required string Kind { get; init; }", eb, StringComparison.Ordinal);
        Assert.Contains("public string? Unit { get; init; }", eb, StringComparison.Ordinal);
        Assert.Contains("public required float Value { get; init; }", eb, StringComparison.Ordinal);
        Assert.Contains("var kind = r.RequiredAttributeString(\"kind\");", eb, StringComparison.Ordinal);
        Assert.Contains("var content = r.ReadFloat();", eb, StringComparison.Ordinal);
        Assert.Contains("Value = content,", eb, StringComparison.Ordinal);
        Assert.True(eb.IndexOf("var kind = ", StringComparison.Ordinal) < eb.IndexOf("var content = ", StringComparison.Ordinal));
    }

    [Fact]
    public void Nillable_dateTime_element_is_a_nullable_property_with_a_seen_flag()
    {
        var ibUri = Uri("jmx_ib");
        var type = new TypeModel("type.Notice", ibUri, null, [], [Element("NoticedAt", ibUri, TypeRef.Simple(Primitive.DateTimeOffset), 1, false, nillable: true)]);
        var files = CSharpEmitter.Emit(SchemaOf("jmx_ib", type), EmptyDictionary);
        var ib = files["InformationBasis.g.cs"];
        Assert.Contains("public DateTimeOffset? NoticedAt { get; init; }", ib, StringComparison.Ordinal);
        Assert.Contains("case \"NoticedAt\" when r.InNamespace(XmlNamespaces.InformationBasis): r.Once(ref noticedAtSeen, \"NoticedAt\"); noticedAt = r.ReadNullableDateTimeOffset(); break;", ib, StringComparison.Ordinal);
        Assert.Contains("NoticedAt = noticedAtSeen ? noticedAt : throw r.Missing(in scope, \"NoticedAt\"),", ib, StringComparison.Ordinal);
    }

    [Fact]
    public void Nillable_element_that_is_not_dateTime_is_rejected()
    {
        var ibUri = Uri("jmx_ib");
        var type = new TypeModel("type.Notice", ibUri, null, [], [Element("NoticedAt", ibUri, TypeRef.Simple(Primitive.String), 1, false, nillable: true)]);
        var ex = Assert.Throws<GeneratorException>(() => CSharpEmitter.Emit(SchemaOf("jmx_ib", type), EmptyDictionary));
        Assert.Equal("type.Notice/NoticedAt: nillable elements are only supported for xs:dateTime", ex.Message, StringComparer.Ordinal);
    }

    [Fact]
    public void Nillable_complex_element_is_rejected()
    {
        var ibUri = Uri("jmx_ib");
        var inner = new TypeModel("type.Inner", ibUri, null, [], []);
        var wrap = new TypeModel("type.Wrap", ibUri, null, [], [Element("Inner", ibUri, TypeRef.Complex(ibUri, "type.Inner"), 1, false, nillable: true)]);
        var ex = Assert.Throws<GeneratorException>(() => CSharpEmitter.Emit(SchemaOf("jmx_ib", wrap, inner), EmptyDictionary));
        Assert.Equal("type.Wrap/Inner: nillable elements are only supported for xs:dateTime", ex.Message, StringComparer.Ordinal);
    }

    [Fact]
    public void Required_list_attribute_reads_uniformly_with_the_other_attribute_types()
    {
        var meteUri = Uri("jmx_mete");
        var type = new TypeModel("type.Band", meteUri, null, [new AttributeModel("levels", Primitive.StringList, true)], []);
        var files = CSharpEmitter.Emit(SchemaOf("jmx_mete", type), EmptyDictionary);
        var mete = files["Meteorology.g.cs"];
        Assert.Contains("public required ImmutableArray<string> Levels { get; init; }", mete, StringComparison.Ordinal);
        Assert.Contains("var levels = r.RequiredAttributeList(\"levels\");", mete, StringComparison.Ordinal);
    }

    [Fact]
    public void Namespace_container_has_a_summary_and_Body_derives_from_ReportBody_with_Parse()
    {
        var seisUri = Uri("jmx_seis");
        var body = new TypeModel("type.Body", seisUri, null, [], []);
        var files = CSharpEmitter.Emit(SchemaOf("jmx_seis", body), EmptyDictionary);
        var seis = files["Seismology.g.cs"];
        Assert.Contains("/// <summary>\n/// XML 名前空間 <c>" + seisUri + "</c> に属する型を格納します。\n/// </summary>\npublic static partial class Seismology\n{", seis, StringComparison.Ordinal);
        Assert.Contains("public sealed record Body : ReportBody\n", seis, StringComparison.Ordinal);
        Assert.Contains("public static Body Parse(XmlReader reader)", seis, StringComparison.Ordinal);
        Assert.Contains("r.MoveToElement(\"Body\", XmlNamespaces.Seismology);", seis, StringComparison.Ordinal);
    }

    [Fact]
    public void Jmx_namespace_types_are_emitted_without_a_wrapping_container_class()
    {
        var jmxUri = Uri("jmx");
        var marker = new TypeModel("type.Marker", jmxUri, null, [], []);
        var files = CSharpEmitter.Emit(SchemaOf("jmx", marker), EmptyDictionary);
        var jmx = files["Jmx.g.cs"];
        Assert.DoesNotContain("public static partial class", jmx, StringComparison.Ordinal);
        Assert.Contains("\npublic sealed record Marker\n", jmx, StringComparison.Ordinal);
    }

    [Fact]
    public void Type_report_is_excluded_from_the_output()
    {
        var jmxUri = Uri("jmx");
        var report = new TypeModel("type.report", jmxUri, null, [], []);
        var kept = new TypeModel("type.Kept", jmxUri, null, [], []);
        var files = CSharpEmitter.Emit(SchemaOf("jmx", report, kept), EmptyDictionary);
        var jmx = files["Jmx.g.cs"];
        Assert.DoesNotContain("record Report", jmx, StringComparison.Ordinal);
        Assert.Contains("public sealed record Kept\n", jmx, StringComparison.Ordinal);
    }

    [Fact]
    public void SchemaInfo_carries_dates_and_versions()
    {
        var schema = new SchemaModel([], [new XsdVersion("sample.xsd", "urn:sample", "9.9", "2020-01-02")]);
        var dictionary = new DictionaryModel("2020-12-31", []);
        var files = CSharpEmitter.Emit(schema, dictionary);
        var info = files["SchemaInfo.g.cs"];
        Assert.Contains("public static string DictionaryDate { get; } = \"2020-12-31\";", info, StringComparison.Ordinal);
        Assert.Contains("new(\"sample.xsd\", \"urn:sample\", \"9.9\", \"2020-01-02\"),", info, StringComparison.Ordinal);
        Assert.Contains("public sealed record SchemaVersion(string File, string Namespace, string Version, string Date);", info, StringComparison.Ordinal);
    }
}
