using System.Collections.Immutable;
using System.Text;

namespace JmaXml.Generator;

public static class CSharpEmitter
{
    private static readonly ImmutableArray<(string Prefix, string XsdType, string Element, string Name, bool IsBody)> Roots =
    [
        ("jmx", "type.control", "Control", "管理部", false),
        ("jmx_ib", "type.head", "Head", "ヘッダ部", false),
        ("jmx_mete", "type.Body", "Body", "気象の内容部", true),
        ("jmx_seis", "type.Body", "Body", "地震の内容部", true),
        ("jmx_volc", "type.Body", "Body", "火山の内容部", true),
    ];

    public static IReadOnlyDictionary<string, string> Emit(SchemaModel schema, DictionaryModel dictionary)
    {
        var files = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var ns in schema.Namespaces)
        {
            var w = new Writer();
            Header(w, "using System.Collections.Immutable;", "using System.Xml;");
            var types = ns.Types.Where(t => t.XsdName != "type.report").ToList();
            if (ns.ClassName is null)
            {
                EmitTypes(w, schema, dictionary, ns, types);
            }
            else
            {
                w.Line("/// <summary>");
                w.Line($"/// XML 名前空間 <c>{ns.Uri}</c> に属する型を格納します。");
                w.Line("/// </summary>");
                w.Line($"public static partial class {ns.ClassName}");
                w.Line("{");
                w.Indent();
                EmitTypes(w, schema, dictionary, ns, types);
                w.Outdent();
                w.Line("}");
            }
            files[$"{ns.ClassName ?? "Jmx"}.g.cs"] = w.ToString();
        }
        files["SchemaInfo.g.cs"] = EmitSchemaInfo(schema, dictionary);
        return files;
    }

    private static void Header(Writer w, params string[] usings)
    {
        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        foreach (var u in usings) w.Line(u);
        w.Line();
        w.Line("namespace JmaXml;");
        w.Line();
    }

    private static void EmitTypes(Writer w, SchemaModel schema, DictionaryModel dictionary, NamespaceModel ns, List<TypeModel> types)
    {
        for (var i = 0; i < types.Count; i++)
        {
            if (i > 0) w.Line();
            EmitType(w, schema, dictionary, ns, types[i]);
        }
    }

    private static void EmitType(Writer w, SchemaModel schema, DictionaryModel dictionary, NamespaceModel ns, TypeModel type)
    {
        ValidateNillableElements(type);
        var name = Naming.TypeName(type.XsdName);
        var dictType = dictionary.Namespace(ns.Prefix)?.Type(type.XsdName);
        var root = Roots.FirstOrDefault(r => r.Prefix == ns.Prefix && r.XsdType == type.XsdName);
        foreach (var line in DocComments.ForType(dictType, root.Name ?? FallbackTypeSummary(schema, dictionary, type) ?? name)) w.Line(line);
        w.Line($"public sealed record {name}{(root.IsBody ? " : ReportBody" : "")}");
        w.Line("{");
        w.Indent();
        var first = true;
        foreach (var attribute in type.Attributes)
        {
            if (!first) w.Line();
            first = false;
            foreach (var line in DocComments.ForMember(dictType?.Attribute(attribute.Name), attribute.Name)) w.Line(line);
            var csType = CSharpType(attribute.Type);
            var property = Naming.PropertyName(attribute.Name);
            w.Line(attribute.Required
                ? $"public required {csType} {property} {{ get; init; }}"
                : $"public {Nullable(csType)} {property} {{ get; init; }}");
        }
        if (type.Content is { } content)
        {
            if (!first) w.Line();
            first = false;
            w.Line("/// <summary>要素の値</summary>");
            var csType = CSharpType(content);
            w.Line(IsNullableType(csType) ? $"public {csType} Value {{ get; init; }}" : $"public required {csType} Value {{ get; init; }}");
        }
        foreach (var element in type.Elements)
        {
            if (!first) w.Line();
            first = false;
            foreach (var line in DocComments.ForMember(dictType?.Element(element.DictKey), element.Name)) w.Line(line);
            w.Line(PropertyDeclaration(ns, element));
        }
        if (root is { Element: not null, Name: not null })
        {
            w.Line();
            EmitParse(w, name, root.Element, root.Name, ns.Prefix);
        }
        w.Line();
        EmitRead(w, ns, type, name);
        w.Outdent();
        w.Line("}");
    }

    private static void ValidateNillableElements(TypeModel type)
    {
        foreach (var element in type.Elements)
        {
            if (element is { Nillable: true, Type.Primitive: not Primitive.DateTimeOffset })
            {
                throw new GeneratorException($"{type.XsdName}/{element.Name}: nillable elements are only supported for xs:dateTime");
            }
        }
    }

    private static string? FallbackTypeSummary(SchemaModel schema, DictionaryModel dictionary, TypeModel type)
    {
        foreach (var ns in schema.Namespaces)
        {
            foreach (var owner in ns.Types)
            {
                foreach (var element in owner.Elements)
                {
                    if (element.Type.Namespace != type.Namespace || element.Type.TypeName != type.XsdName) continue;
                    var meaning = dictionary.Namespace(ns.Prefix)?.Type(owner.XsdName)?.Element(element.DictKey)?.Meaning;
                    if (!string.IsNullOrEmpty(meaning)) return meaning;
                }
            }
        }
        return null;
    }

    private static string PropertyDeclaration(NamespaceModel ns, ElementModel element)
    {
        var property = Naming.PropertyName(element.Name);
        var itemType = ElementItemType(ns, element);
        if (element.Unbounded)
        {
            return element.MinOccurs == 0
                ? $"public ImmutableArray<{itemType}> {property} {{ get; init; }} = [];"
                : $"public required ImmutableArray<{itemType}> {property} {{ get; init; }}";
        }
        if (element.MinOccurs == 1 && !IsNullableType(itemType)) return $"public required {itemType} {property} {{ get; init; }}";
        return $"public {Nullable(itemType)} {property} {{ get; init; }}";
    }

    private static void EmitParse(Writer w, string name, string element, string japanese, string prefix)
    {
        w.Line("/// <summary>");
        w.Line($"/// 指定した <see cref=\"XmlReader\"/> から{japanese}を読み込みます。");
        w.Line("/// </summary>");
        w.Line($"/// <param name=\"reader\"><c>{element}</c> 要素、またはその手前の位置にある <see cref=\"XmlReader\"/>。呼び出し元が生成した設定をそのまま使用します。</param>");
        w.Line($"/// <returns>読み込んだ{japanese}。</returns>");
        w.Line("/// <exception cref=\"ArgumentNullException\"><paramref name=\"reader\"/> が <see langword=\"null\" /> です。</exception>");
        w.Line("/// <exception cref=\"XmlException\">XML の解析でエラーが発生しました。</exception>");
        w.Line($"/// <exception cref=\"JmaXmlException\">{japanese}を読み込めません。</exception>");
        w.Line("/// <remarks>");
        w.Line($"/// 読み込みに成功すると、<paramref name=\"reader\"/> は <c>{element}</c> の終了タグの次のノードに位置します。");
        w.Line("/// </remarks>");
        w.Line($"public static {name} Parse(XmlReader reader)");
        w.Line("{");
        w.Indent();
        w.Line("ArgumentNullException.ThrowIfNull(reader);");
        w.Line("var r = new JmaXmlReader(reader);");
        w.Line($"r.MoveToElement(\"{element}\", {NamespaceExpression(prefix)});");
        w.Line("return Read(r);");
        w.Outdent();
        w.Line("}");
    }

    private static void EmitRead(Writer w, NamespaceModel ns, TypeModel type, string name)
    {
        w.Line($"internal static {name} Read(JmaXmlReader r)");
        w.Line("{");
        w.Indent();
        var inits = new List<string>();
        foreach (var attribute in type.Attributes)
        {
            var local = Naming.LocalName(attribute.Name);
            w.Line($"var {local} = r.{AttributeMethod(type, attribute)}(\"{attribute.Name}\");");
            inits.Add($"{Naming.PropertyName(attribute.Name)} = {local},");
        }
        if (type.Content is { } content)
        {
            w.Line($"var content = r.{ReadMethod(content, false)}();");
            inits.Add("Value = content,");
        }
        else
        {
            foreach (var element in type.Elements)
            {
                var local = Naming.LocalName(element.Name);
                var itemType = ElementItemType(ns, element);
                if (element.Unbounded)
                {
                    w.Line($"ArrayBuilder<{itemType}> {local} = default;");
                }
                else
                {
                    w.Line($"{Nullable(itemType)} {local} = null;");
                    w.Line($"var {local}Seen = false;");
                }
            }
            w.Line("using var scope = r.Enter();");
            w.Line("while (r.NextChild())");
            w.Line("{");
            w.Indent();
            w.Line("switch (r.LocalName)");
            w.Line("{");
            w.Indent();
            foreach (var element in type.Elements)
            {
                var local = Naming.LocalName(element.Name);
                var read = element.Type.IsComplex
                    ? $"{GlobalTypeName(element.Type)}.Read(r)"
                    : $"r.{ReadMethod(element.Type.Primitive!.Value, element.Nillable)}()";
                var nsExpr = NamespaceExpression(SchemaLoader.PrefixOf(element.Namespace));
                w.Line(element.Unbounded
                    ? $"case \"{element.Name}\" when r.InNamespace({nsExpr}): {local}.Add(r, {read}); break;"
                    : $"case \"{element.Name}\" when r.InNamespace({nsExpr}): r.Once(ref {local}Seen, \"{element.Name}\"); {local} = {read}; break;");
            }
            w.Line("default: r.Skip(); break;");
            w.Outdent();
            w.Line("}");
            w.Outdent();
            w.Line("}");
            foreach (var element in type.Elements)
            {
                var local = Naming.LocalName(element.Name);
                var property = Naming.PropertyName(element.Name);
                var itemType = ElementItemType(ns, element);
                if (element.Unbounded)
                {
                    inits.Add(element.MinOccurs == 0
                        ? $"{property} = {local}.ToImmutable(r),"
                        : $"{property} = {local}.IsEmpty ? throw r.Missing(\"{element.Name}\") : {local}.ToImmutable(r),");
                }
                else if (element.MinOccurs == 0)
                {
                    inits.Add($"{property} = {local},");
                }
                else if (IsNullableType(itemType))
                {
                    inits.Add($"{property} = {local}Seen ? {local} : throw r.Missing(\"{element.Name}\"),");
                }
                else
                {
                    inits.Add($"{property} = {local} ?? throw r.Missing(\"{element.Name}\"),");
                }
            }
        }
        w.Line($"return new {name}");
        w.Line("{");
        w.Indent();
        foreach (var init in inits) w.Line(init);
        w.Outdent();
        w.Line("};");
        w.Outdent();
        w.Line("}");
    }

    private static string EmitSchemaInfo(SchemaModel schema, DictionaryModel dictionary)
    {
        var w = new Writer();
        Header(w, "using System.Collections.Immutable;");
        w.Line("/// <summary>");
        w.Line("/// 生成元となった公式資料の版を表します。");
        w.Line("/// </summary>");
        w.Line("public static class SchemaInfo");
        w.Line("{");
        w.Indent();
        w.Line("/// <summary>");
        w.Line("/// 辞書の日付を取得します。");
        w.Line("/// </summary>");
        w.Line($"public static string DictionaryDate {{ get; }} = \"{dictionary.Date}\";");
        w.Line();
        w.Line("/// <summary>");
        w.Line("/// XSD ごとの版と改版日を取得します。");
        w.Line("/// </summary>");
        w.Line("public static ImmutableArray<SchemaVersion> Schemas { get; } =");
        w.Line("[");
        w.Indent();
        foreach (var v in schema.Versions) w.Line($"new(\"{v.File}\", \"{v.Namespace}\", \"{v.Version}\", \"{v.Date}\"),");
        w.Outdent();
        w.Line("];");
        w.Outdent();
        w.Line("}");
        w.Line();
        w.Line("/// <summary>");
        w.Line("/// XSD ファイル 1 本の版を表します。");
        w.Line("/// </summary>");
        w.Line("/// <param name=\"File\">ファイル名。</param>");
        w.Line("/// <param name=\"Namespace\">対象名前空間。</param>");
        w.Line("/// <param name=\"Version\">版。</param>");
        w.Line("/// <param name=\"Date\">改版日（<c>yyyy-MM-dd</c> 形式）。</param>");
        w.Line("public sealed record SchemaVersion(string File, string Namespace, string Version, string Date);");
        return w.ToString();
    }

    private static string ElementItemType(NamespaceModel ns, ElementModel element)
    {
        if (element.Type.IsComplex) return QualifiedTypeName(ns, element.Type);
        var primitive = element.Type.Primitive!.Value;
        if (primitive == Primitive.DateTimeOffset && element.Nillable) return "DateTimeOffset?";
        return CSharpType(primitive);
    }

    private static string QualifiedTypeName(NamespaceModel ns, TypeRef type)
    {
        var name = Naming.TypeName(type.TypeName!);
        if (type.Namespace == ns.Uri) return name;
        var className = SchemaLoader.KnownNamespaces.First(n => n.Uri == type.Namespace).ClassName;
        return className is null ? name : $"{className}.{name}";
    }

    private static string GlobalTypeName(TypeRef type)
    {
        var name = Naming.TypeName(type.TypeName!);
        var className = SchemaLoader.KnownNamespaces.First(n => n.Uri == type.Namespace).ClassName;
        return className is null ? $"global::JmaXml.{name}" : $"global::JmaXml.{className}.{name}";
    }

    private static string NamespaceExpression(string prefix) =>
        "XmlNamespaces." + (SchemaLoader.KnownNamespaces.First(n => n.Prefix == prefix).ClassName ?? "Jmx");

    private static string CSharpType(Primitive primitive) => primitive switch
    {
        Primitive.String or Primitive.Token => "string",
        Primitive.StringList => "ImmutableArray<string>",
        Primitive.Float => "float",
        Primitive.NullableFloat => "float?",
        Primitive.Int => "int",
        Primitive.NullableInt => "int?",
        Primitive.Byte => "byte",
        Primitive.Bool => "bool",
        Primitive.DateTimeOffset => "DateTimeOffset",
        Primitive.Duration => "TimeSpan",
        _ => throw new ArgumentOutOfRangeException(nameof(primitive)),
    };

    private static string ReadMethod(Primitive primitive, bool nillable) => primitive switch
    {
        Primitive.String => "ReadString",
        Primitive.Token => "ReadToken",
        Primitive.StringList => "ReadList",
        Primitive.Float => "ReadFloat",
        Primitive.NullableFloat => "ReadNullableFloat",
        Primitive.Int => "ReadInt",
        Primitive.NullableInt => "ReadNullableInt",
        Primitive.Byte => "ReadByte",
        Primitive.Bool => "ReadBool",
        Primitive.DateTimeOffset => nillable ? "ReadNullableDateTimeOffset" : "ReadDateTimeOffset",
        Primitive.Duration => "ReadDuration",
        _ => throw new ArgumentOutOfRangeException(nameof(primitive)),
    };

    private static string AttributeMethod(TypeModel type, AttributeModel attribute)
    {
        if (attribute is { Type: Primitive.StringList, Required: false })
        {
            throw new GeneratorException($"{type.XsdName}/@{attribute.Name}: optional list attributes are not supported");
        }
        var suffix = attribute.Type switch
        {
            Primitive.String => "String",
            Primitive.Token => "Token",
            Primitive.StringList => "List",
            Primitive.Float => "Float",
            Primitive.Int => "Int",
            Primitive.Byte => "Byte",
            Primitive.Bool => "Bool",
            _ => throw new GeneratorException($"Attribute '{attribute.Name}' has unsupported type {attribute.Type}"),
        };
        return (attribute.Required ? "RequiredAttribute" : "Attribute") + suffix;
    }

    private static bool IsNullableType(string csType) => csType.EndsWith('?');

    private static string Nullable(string csType) => IsNullableType(csType) ? csType : csType + "?";

    private sealed class Writer
    {
        private readonly StringBuilder _sb = new();
        private int _indent;

        public void Indent() => _indent++;

        public void Outdent() => _indent--;

        public void Line(string text = "")
        {
            if (text.Length > 0) _sb.Append(' ', _indent * 4).Append(text);
            _sb.Append('\n');
        }

        public override string ToString() => _sb.ToString();
    }
}

public sealed class GeneratorException(string message) : Exception(message);
